### ISSUE TITLE
Can not run reports "Wails applications will not build without the correct build tags."?

### ISSUE THREAD

**Issue by xbpk3t** [gphper/toolbox#1]
According to this post [Golang build tags not working with wails build · Issue #1610 · wailsapp/wails](https://github.com/wailsapp/wails/issues/1610), I set GOOS and GOARCH, but still report this error, so how to solve?

**Comment by gphper** [comment]
I completed the operation under the Windows 10 system, and have not tried other systems. You can first follow the official Wails tutorial to see if you can try running the sample project on your own computer

**Comment by xbpk3t** [comment]
thx for the reply, running `wails dev` works fine.
